### ISSUE TITLE
Adding messages to debugbar, and twig bridge

### ISSUE THREAD

**Issue by matthijsthoolen** [bearlikelion/twig-debugbar#3]
Hello,

Thank you for the plugin. 

I was trying to use the plugin with Twig, but couldn't figure it out how to add debugbar message and make a Twig bridge for twig loading times etc. 

The debugbar is now working with Twig and the debugbar is shown on all pages. But I can't figure out how to add messages. Normally this would be able with $debugbar["messages"]->addMessage("hello world!"); 

I tried to add a message in the Extension __constructor with $this->debugbar, and that showed a message in the debugbar. But how can I add it from the outside the class?

Also how can I add the twig bridge? 

Thanks in advance!

**Comment by bearlikelion** [comment]
Added dbg_message('text', 'label')

These messages can only be sent from within a rendered twig template, but could be used to replace Twig's debug extension since it can handle arrays and objects.

There needs to be a way to extend the extension to PHP so you can add messages from outside of twig, this functionality would also allow me to enable Timers.

**Comment by matthijsthoolen** [comment]
Thanks a lot for the quick reply and fix. 

I will try the functionallity another time! Do you know a (simple) way to extend the extension to PHP? 
Maybe it's an option to add another array variabele to the constructor? And add this array (eventually with a loop) to the debugbar inside the extension?

Also about my other question, do you know a way to get the twig bridge working?

**Comment by bearlikelion** [comment]
I'm not exactly sure what you mean by a twig bridge? The library _is_ a twig-extension, so its providing custom PHP utility to Twig natively.

As far as extending it, wrapping it in a service container would be a good place to start. This way we could load the extension as is into Twig, and then have the base library load the Debug Bar with some additional functionality to extend it.

What I mean by this, is something similar to:

``` PHP
<?php
...
$debug = $this->container->get('DebugBar'); // new Bearlikelion\TwigDebugBar\Class()
$debug->startTimer('testing', 'debug');
...
```

``` html
<body>
...
<!-- Stop timer -->
{{ dbg_stopTimer('testing') }} 
...
</body>
```

But it would require me to refactor this library

**Comment by matthijsthoolen** [comment]
This is what I mean with the twig bridge: http://phpdebugbar.com/docs/bridge-collectors.html#twig

I will try to figure out how I can add messages from PHP, I may have an idea. I will give you an update if I have something interesting.
